### ISSUE TITLE
Bug: adwm keeps making polybar transparent.

### ISSUE THREAD

**Issue by sagotsky** [bbidulock/adwm#14]
Hi there.  I'm WM hopping in an attempt to switch off of xmonad.  adwm looks great so far and checks all the boxes I've been looking for, but I'm having a nagging issue with my bar of choice, polybar.  

When I load up adwm, polybar looks great.  When I mouse over it, it continues to look great.  When the mouse leaves, it becomes semi transparent until I mouse back to it.  

I haven't had this issue in other window managers.  I'm experiencing it with both picom and xcompmgr (xcompmgr does try to fade all windows on mouse exit, which I'm not a fan of).  I've set `Adwm*opacity` to `1.0`, but I'm not confident that's the right setting since it hasn't made a noticeable change.

Thanks!

**Comment by bbidulock** [comment]
Be sure to check out awesome and spectrwm.  I might not have written this if I knew about spectrwm earlier.  I'm the same way about bars, so I feel your pain there.

With regard to your problem, I think that the Adwm*opacity setting is really a hint to the composite manager on what transparency to use for window-manager decorations, not the window itself.

Adwm is placing and removing _NET_WM_FOCUS on the parent window of the dock per EWMH/NETWM specifications.  Some other window managers might not do this correctly for all window types.  xcompmgr and picom see this and give the dock "unfocused window" transparency.  However, both xcompmgr and picom allow you to use settings to ignore placing traparency effects on windows by name and class.  So, use xwininfo to find the name and class of the dock and add it to settings on your composite manager (telling it to ignore your dock).  If that doesn't work for you or you have difficulties doing that, let me know and I will try to help further.

**Comment by sagotsky** [comment]
I've tried both.  Spectrwm almost nailed it, but felt a little janky.  I'll give it another shot though since I haven't been totally sold on anything yet.

TY for the explanation.  Happy to close this out if it's actually behaving according to spec.

Cheers!
