### ISSUE TITLE
Having trouble getting adwm-git, from the Arch User Repository, to compile. 

### ISSUE THREAD

**Issue by padmakunga** [bbidulock/adwm#17]
I have been trying to get both adwm and adwm-git to compile on my ArchLinux system.

Kernel: 5.15.2-arch1-1
CPU: Intel Pentium G3220 (2) @ 3.000GHz
GPU: AMD ATI Radeon HD 7570
GPU: Intel HD Graphics
Memory: 6894MiB
Compiler: gcc 11.1.0-1
                gcc-libs 11.1.0-1
                lib32-gcc-libs 11.1.0-1
-----------------------------------------------------------
==> Making package: adwm-git 0.7.12.r4.gffc97df-1 (Thu 18 Nov 2021 04:53:56 AM CST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating adwm-git git repo...
Fetching origin
==> Validating source files with md5sums...
    adwm-git ... Skipped
==> Extracting sources...
  -> Creating working copy of adwm-git git repo...
Switched to a new branch 'makepkg'
==> Starting prepare()...
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'scripts'.
libtoolize: copying file 'scripts/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: configure.ac: not using Intltool
autoreconf: configure.ac: not using Gtkdoc
autoreconf: running: aclocal --force -I m4
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:20: installing 'scripts/compile'
configure.ac:33: installing 'scripts/missing'
src/Makefile.am: installing 'scripts/depcomp'
autoreconf: Leaving directory '.'
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for wchar.h... yes
checking for minix/config.h... no
checking for vfork.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking whether _XOPEN_SOURCE should be defined... no
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports the include directive... yes (GNU style)
checking whether make supports nested variables... yes
checking how to create a pax tar archive... gnutar
checking dependency style of gcc... gcc3
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports nested variables... (cached) yes
checking for a sed that does not truncate output... /usr/bin/sed
checking for gawk... (cached) gawk
checking for gcc... (cached) gcc
checking whether the compiler supports GNU C... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to enable C11 features... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking how to run the C preprocessor... gcc -E
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking for ar... ar
checking the archiver (ar) interface... ar
checking for markdown... markdown
checking for asciidoc... asciidoc
checking for a2x... a2x
checking for lynx... lynx
checking for a sed that does not truncate output... (cached) /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking how to print strings... printf
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for shl_load... no
checking for shl_load in -ldld... no
checking for dlopen... no
checking for dlopen in -ldl... yes
checking whether a program can dlopen itself... yes
checking whether a statically linked program can dlopen itself... no
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.14.0... yes
## ------------ ##
checking for g++... g++
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for egrep... (cached) /usr/bin/grep -E
checking for X... libraries , headers 
checking for gethostbyname... yes
checking for connect... yes
checking for remove... yes
checking for shmat... yes
checking for IceConnectionNumber in -lICE... yes
checking for fcntl.h... yes
checking for locale.h... yes
checking for malloc.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for strings.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/time.h... yes
checking for _Bool... yes
checking for stdbool.h that conforms to C99... yes
## ------------------------------ ##
checking for pid_t... yes
checking for size_t... yes
checking for off_t... yes
checking for uid_t in sys/types.h... yes
## ----------------- ##
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking whether lstat correctly handles trailing slash... yes
checking for GNU libc compatible malloc... yes
checking for GNU libc compatible realloc... yes
checking for getcwd... yes
checking for memmove... yes
checking for regcomp... yes
checking for select... yes
checking for setlocale... yes
checking for strchr... yes
checking for strdup... yes
checking for strerror... yes
checking for strrchr... yes
checking for atexit... yes
checking for floor... no
checking for gethostname... yes
checking for gettimeofday... yes
checking for memset... yes
checking for sqrt... no
checking for strcasecmp... yes
checking for strncasecmp... yes
checking for strndup... yes
checking for strspn... yes
checking for strstr... yes
checking for strtol... yes
checking for strtoul... yes
checking for working strnlen... yes
checking for working strtod... yes
## ----------------------- ##
checking for X11... yes
checking for XFIXES... yes
checking for XDAMAGE... yes
checking for XCOMPOSITE... yes
checking for XRANDR... yes
checking for XINERAMA... yes
checking for XSYNC... yes
checking for XSHAPE... yes
checking for SMLIB... yes
checking for SN... yes
## ------------------- ##
checking for XRENDER... yes
checking for xrender use... no
checking for PIXBUF... yes
checking for gdk-pixbuf use... no
checking for IMLIB2... yes
checking for imlib2 use... no
checking for XCAIRO... yes
checking for xcairo use... no
## ----------------------- ##
checking for XPM... yes
checking for LIBPNG... yes
checking for LIBJPEG... yes
checking for LIBSVG... yes
## -------------- ##
checking for XFT... yes
checking for xft use... no
checking for PANGOXFT... yes
checking for pango xft use... no
checking for PANGOCAIRO... yes
checking for pango cairo use... no
checking for debug support... no
## ------------------------------ ##
checking for blackbox support... no
checking for fluxbox support... no
checking for icewm support... no
checking for openbox support... no
checking for metacity support... no
checking for mutter support... no
checking for pekwm support... no
checking for waimea support... no
checking for wmaker support... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating doc/Makefile
config.status: creating doc/adwm.1
config.status: creating doc/adwm-config.5
config.status: creating doc/adwm-keys.5
config.status: creating doc/adwm-buttons.5
config.status: creating doc/adwm-rules.5
config.status: creating doc/adwm-style.5
config.status: creating doc/adwm-theme.5
config.status: creating doc/adwm-dock.5
config.status: creating data/Makefile
config.status: creating src/autoconf.h
config.status: src/autoconf.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
Making all in src
make[1]: Entering directory '/home/tree/.builds/adwm-git/src/adwm-git/src'
make  all-am
make[2]: Entering directory '/home/tree/.builds/adwm-git/src/adwm-git/src'
  CC       adwm.o
adwm.c: In function ‘main’:
adwm.c:7027:25: error: format not a string literal and no format arguments [-Werror=format-security]
 7027 |                         snprintf(conf, sizeof(conf) - 1, optarg);
      |                         ^~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [Makefile:871: adwm.o] Error 1
make[2]: Leaving directory '/home/tree/.builds/adwm-git/src/adwm-git/src'
make[1]: *** [Makefile:627: all] Error 2
make[1]: Leaving directory '/home/tree/.builds/adwm-git/src/adwm-git/src'
make: *** [Makefile:470: all-recursive] Error 1
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by mbwoodcraft** [comment]
btw, thank you for your extensive work and maintenance of window managers and associated tools and libraries!

**Comment by bbidulock** [comment]
Sorry for the late reply: both packages should build flawlessly again.  Problem was the addition of a -Werror=format-security CFLAG to makepkg.conf.  If that works for you, you can close this issue.
