### ISSUE TITLE
not compiling on debian testing

### ISSUE THREAD

**Issue by netfun81** [bbidulock/adwm#2]
launching the script ./autogen.sh gives the following message: 

configure.ac:32: error: possibly undefined macro: AC_DISABLE_STATIC
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:64: error: possibly undefined macro: AC_DEFINE
autoreconf: /usr/bin/autoconf failed with exit status: 1

compiled fine in the past on Arch linux.   I can get around this error but wanted to let you know.

**Comment by bbidulock** [comment]
Need to clean your working tree or do:

    autoreconf -fiv
