### ISSUE TITLE
im having this weird problem with the aur version of those xde packages that you mention in the github page 

### ISSUE THREAD

**Issue by soyDESKTOP68A2MRFT** [bbidulock/adwm#22]
`En el fichero incluido desde wnckprop.c:47:
../libwnck/libwnck.h:41:10: error fatal: libwnck/wnck-enum-types.h: No existe el fichero o el directorio
   41 | #include <libwnck/wnck-enum-types.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilación terminada.
make[2]: *** [Makefile:896: wnckprop.o] Error 1
make[2]: se sale del directorio '/home/juan/.cache/yay/libwnck+-git/src/libwnck+-git/libwnck'
make[1]: *** [Makefile:562: all-recursive] Error 1
make[1]: se sale del directorio '/home/juan/.cache/yay/libwnck+-git/src/libwnck+-git'
make: *** [Makefile:469: all] Error 2
==> ERROR: Se produjo un fallo en build().
    Cancelando...
 -> error compilando: libwnck+-git
juan-hppaviliong4notebookpc:[juan]:~$`

**Comment by soyDESKTOP68A2MRFT** [comment]
basically it says that "wnck-enum-types.h" doesn't exist what that means (i say you this because the output it's in spanish)

**Comment by bbidulock** [comment]
Which package are you trying to compile?  If not ADWM, please report under the github issues associated with the xde package.
