### ISSUE TITLE
Build Failed (tried: master and tag: 0.7.2)

### ISSUE THREAD

**Issue by mpolitzer** [bbidulock/adwm#4]
Tried to build the project but couldn't, what I did:
Build error in error.log below

#####################
git checkout 0.7.2
./autogen.sh
./configure > configure.log
make
#####################

Linux: Gentoo

[error.log](https://github.com/bbidulock/adwm/files/1740231/error.log)
[configure.log](https://github.com/bbidulock/adwm/files/1740240/configure.log)

**Comment by bbidulock** [comment]
It appears you are missing libxpm, load it and you should no longer have a problem.  I suppose `configure` should error out when it is not present...

**Comment by mpolitzer** [comment]
Build got further along after installing libXpm, after that got a link error:

adwm.c:6258: error: undefined reference to 'getappl'
adwm.c:5577: error: undefined reference to 'removeappl'

Got it to compile after installing startup-notification, which also seem to also be mandatory

**Comment by bbidulock** [comment]
I use the following dependencies ffor the Archlinux build:

    libxft libxrandr libxinerama libxpm startup-notification libxcomposite libxdamage

I also add the following for default key bindings:

    xdg-launch xde-ctools xde-menu xde-session
