### ISSUE TITLE
build failure with libtool thing

### ISSUE THREAD

**Issue by SolarAquarion** [bbidulock/adwm#6]
libtool:   error: cannot find the library 'adwm-adwm.la' or unhandled argument 'adwm-adwm.la'

**Comment by bbidulock** [comment]
Happened to me once too.  Try ./rebuild.sh  or at least 'make clean' then 'make'.

**Comment by SolarAquarion** [comment]
btw, it was the aur package, and also the roxterm git is the real source and not a fork

**Comment by milkmiruku** [comment]
Hmm, I'm having trouble upgrading `adwm-git` also. I deleted my `yay` cache adwm directory, but it still failed with the same error as OP.

I did a clean clone, `./autogen.sh`, `./configure.sh`, then `make` and got this:

```
Making all in src
make[1]: Entering directory '/home/milk/src/adwm/src'
make  all-am
make[2]: Entering directory '/home/milk/src/adwm/src'
  CC       adwm.o
  CC       actions.o
  CC       config.o
  CC       draw.o
  CC       imlib.o
  CC       pixbuf.o
  CC       xcairo.o
  CC       render.o
  CC       ximage.o
  CC       xlib.o
  CC       ewmh.o
  CC       image.o
  CC       layout.o
  CC       parse.o
  CC       resource.o
  CC       tags.o
  CC       texture.o
  CC       icons.o
  CC       session.o
  CC       save.o
  CCLD     adwm
libtool:   error: cannot find the library 'adwm-adwm.la' or unhandled argument 'adwm-adwm.la'
make[2]: *** [Makefile:807: adwm] Error 1
make[2]: Leaving directory '/home/milk/src/adwm/src'
make[1]: *** [Makefile:617: all] Error 2
make[1]: Leaving directory '/home/milk/src/adwm/src'
make: *** [Makefile:461: all-recursive] Error 1
make  34.33s user 2.68s system 97% cpu 37.794 total
```

Then I did `./rebuild.sh` and that worked and left me with an `adwm` etc. in src.

**Comment by bbidulock** [comment]
Both build fine for me, both with makepkg  on a full blown system as well as in a clean chroot for both 64 and 32.

**Comment by milkmiruku** [comment]
Very confusing. I'm stuck not being able to do a full system upgrade with `yay`. I'll try to build with `mkchrootpkg`, as soon as I can figure out how to get the chroot to syncdeps from the net..

**Comment by bbidulock** [comment]
[aurbuild.tar.gz](https://github.com/bbidulock/adwm/files/2480088/aurbuild.tar.gz)

That's what I use (the ``makem`` script in the tarball) for creating a 64- and 32-bit chroot in a  development directory (I usually put it in /u8/aur).  After the chroot is created you can

    arch-nspawn /u8/aur/64/root

to get into the chroot.  You can do ``yaourt -Syu`` from there to update the chroot.  CTRL-D to exit.  The [custom] repository defined in pacman{32,64}.conf goes to my AUR repo which contains all my AUR packages.  In fact you can just download my pre-built adwm package from there.
