### ISSUE TITLE
error: cannot find the library 'adwm-adwm.la' or unhandled argument 'adwm-adwm.la'

### ISSUE THREAD

**Issue by boxxxie** [bbidulock/adwm#7]
I get this error when installing the package from yaourt, and from instructions on the git page
i get this while running `make`

**Comment by boxxxie** [comment]
i'm not compiling form AUR (i tried though).
i do have base-devel programs installed.
i actually am compiling a fork of [dwm](https://github.com/xorgy/ldwm), and running it as my wm.

this is why i'm not sure why adwm doesn't compile for me.

**Comment by VanLaser** [comment]
I have this same exact error (also on Arch Linux), happens without building from AUR, but by direct cloning and following instructions on the main project page.

**Comment by bluntphenomena** [comment]
any updates how to fix this?

**Comment by bbidulock** [comment]
No, I have no problems building this in any of these ways.

**Comment by bbidulock** [comment]
If you are building under Arch Linux I suggest that you build in a clean chroot.

**Comment by mxmilkb** [comment]
Confirmed fix with `make -j8 clean all`. That's.. strange. @bbidulock Could you edit the PKGBUILDs to use that method?

**Comment by bbidulock** [comment]
I finally found this.  Needed to force dependency between adwm and adwm-adwm.la even though adwm-adwm.la is included in adwm's LDFLAGS.  Someone must have changed automake in this regard.  So added it manually.

**Comment by mxmilkb** [comment]
`0.7.9.r0.g6afb774-1` built successfully here.

**Comment by bbidulock** [comment]
I think this is done, then.
