### ISSUE TITLE
Panel gets focus and can be accidentally closed

### ISSUE THREAD

**Issue by izobilje** [bbidulock/adwm#8]
I am using latest adwm-git on Arch Linux with setting: _Adwm*sloppy: 2_

Whenever mouse gets over Tint2 panel (also tested with Bmpanel2), it gets focus, and often I close it by accident, with keyboard shortcut, instead of window.
(This sometimes crashes ADWM, but that's another issue.)
I couldn't find any way to prevent panel getting focus.

**Comment by bbidulock** [comment]
Annoying.  I didn't notice as I don't use Alt+q much anymore.  Will add feature to suppress window close actions on non-normal window types.

**Comment by bbidulock** [comment]
The mislabelled commit 87690f9674d5fe78cae877f2a16fe576d36746a1 fixes this.  It turned out that keyboard close was the only way of closing not checking whether the window was allowed to be closed (which it wasn't for docks and panels already).  Will generate a maintenance release with the fix as this was rather annoying.

**Comment by bbidulock** [comment]
Okay, please check if release 0.7.6 gets rid of this problem for you.  It might also get rid of the crash you mentioned:  Alt+q on the "dock" as crashing before the fix, so if you had dockapps and pressed Alt+q once more after the panel closed, you would have gotten a crash.  This was the first time in over a year I got adwm to crash (and I use it daily).  Please close the issue if you find it is resolved.

**Comment by izobilje** [comment]
Thanks! Panel doesn't close anymmore in 0.7.6. I couldn't reproduce that rare crash in previous version, but it happened only when panel was accidentaly closed. I didn't have any dockapps.
