### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by Awan** [bbidulock/adwm#9]
compiled both maintenance and stable releases, getting same error.

Making all in src
make[1]: Entering directory '/home/ak/sys/downloads/adwm-0.7.9/src'
make  all-am
make[2]: Entering directory '/home/ak/sys/downloads/adwm-0.7.9/src'
  CC       xcairo.o
xcairo.c: In function ‘xcairo_initxpm’:
xcairo.c:212:2: error: unknown type name ‘XpmAttributes’; did you mean ‘PangoAttribute’?
  XpmAttributes xa = {
  ^~~~~~~~~~~~~
  PangoAttribute
xcairo.c:213:3: error: field name not in record or union initializer
   .visual = DefaultVisual(dpy, scr->screen),
   ^
xcairo.c:213:3: note: (near initialization for ‘xa’)
xcairo.c:213:13: warning: initialization of ‘int’ from ‘Visual *’ {aka ‘struct <anonymous> *’} makes integer from pointer without a cast [-Wint-conversion]
   .visual = DefaultVisual(dpy, scr->screen),
             ^~~~~~~~~~~~~
xcairo.c:213:13: note: (near initialization for ‘xa’)
xcairo.c:214:3: error: field name not in record or union initializer
   .colormap = DefaultColormap(dpy, scr->screen),
   ^
xcairo.c:214:3: note: (near initialization for ‘xa’)
xcairo.c:214:15: warning: excess elements in scalar initializer
   .colormap = DefaultColormap(dpy, scr->screen),
               ^~~~~~~~~~~~~~~
xcairo.c:214:15: note: (near initialization for ‘xa’)
xcairo.c:215:3: error: field name not in record or union initializer
   .depth = DefaultDepth(dpy, scr->screen),
   ^
xcairo.c:215:3: note: (near initialization for ‘xa’)
xcairo.c:215:12: warning: excess elements in scalar initializer
   .depth = DefaultDepth(dpy, scr->screen),
            ^~~~~~~~~~~~
xcairo.c:215:12: note: (near initialization for ‘xa’)
xcairo.c:216:3: error: field name not in record or union initializer
   .valuemask = XpmVisual| XpmColormap| XpmDepth,
   ^
xcairo.c:216:3: note: (near initialization for ‘xa’)
xcairo.c:216:16: error: ‘XpmVisual’ undeclared (first use in this function); did you mean ‘Visual’?
   .valuemask = XpmVisual| XpmColormap| XpmDepth,
                ^~~~~~~~~
                Visual
xcairo.c:216:16: note: each undeclared identifier is reported only once for each function it appears in
xcairo.c:216:27: error: ‘XpmColormap’ undeclared (first use in this function); did you mean ‘XNColormap’?
   .valuemask = XpmVisual| XpmColormap| XpmDepth,
                           ^~~~~~~~~~~
                           XNColormap
xcairo.c:216:40: error: ‘XpmDepth’ undeclared (first use in this function); did you mean ‘xDepth’?
   .valuemask = XpmVisual| XpmColormap| XpmDepth,
                                        ^~~~~~~~
                                        xDepth
xcairo.c:216:16: warning: excess elements in scalar initializer
   .valuemask = XpmVisual| XpmColormap| XpmDepth,
                ^~~~~~~~~
xcairo.c:216:16: note: (near initialization for ‘xa’)
xcairo.c:219:11: warning: implicit declaration of function ‘XpmReadFileToPixmap’; did you mean ‘XCreatePixmap’? [-Wimplicit-function-declaration]
  status = XpmReadFileToPixmap(dpy, scr->drawable, path, &draw, &mask, &xa);
           ^~~~~~~~~~~~~~~~~~~
           XCreatePixmap
xcairo.c:220:16: error: ‘XpmSuccess’ undeclared (first use in this function); did you mean ‘Success’?
  if (status != XpmSuccess || !draw) {
                ^~~~~~~~~~
                Success
xcairo.c:224:2: warning: implicit declaration of function ‘XpmFreeAttributes’; did you mean ‘XSetLineAttributes’? [-Wimplicit-function-declaration]
  XpmFreeAttributes(&xa);
  ^~~~~~~~~~~~~~~~~
  XSetLineAttributes
xcairo.c:228:84: error: request for member ‘width’ in something not a structure or union
  surf = cairo_xlib_surface_create_with_xrender_format(dpy, draw, screen, format, xa.width, xa.height);
                                                                                    ^
xcairo.c:228:94: error: request for member ‘height’ in something not a structure or union
  surf = cairo_xlib_surface_create_with_xrender_format(dpy, draw, screen, format, xa.width, xa.height);
                                                                                              ^
xcairo.c:239:85: error: request for member ‘width’ in something not a structure or union
   clip = cairo_xlib_surface_create_with_xrender_format(dpy, mask, screen, format, xa.width, xa.height);
                                                                                     ^
xcairo.c:239:95: error: request for member ‘height’ in something not a structure or union
   clip = cairo_xlib_surface_create_with_xrender_format(dpy, mask, screen, format, xa.width, xa.height);
                                                                                               ^
xcairo.c:264:12: error: request for member ‘width’ in something not a structure or union
  px->w = xa.width;
            ^
xcairo.c:265:12: error: request for member ‘height’ in something not a structure or union
  px->h = xa.height;
            ^
xcairo.c:266:12: error: request for member ‘depth’ in something not a structure or union
  px->d = xa.depth;
            ^
make[2]: *** [Makefile:861: xcairo.o] Error 1
make[2]: Leaving directory '/home/ak/sys/downloads/adwm-0.7.9/src'
make[1]: *** [Makefile:619: all] Error 2
make[1]: Leaving directory '/home/ak/sys/downloads/adwm-0.7.9/src'
make: *** [Makefile:462: all-recursive] Error 1

**Comment by bbidulock** [comment]
Need more info than that.  What were the arguments to and the results of `./configure`?

**Comment by Awan** [comment]
╭─ak@nix in ~/git/adwm on master ✘ (origin/master) ✉ 2
╰ ▸▸▸▸▸▸▹▹▹▹ + ❤ ./configure --disable-silent-rules
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports the include directive... yes (GNU style)
checking whether make supports nested variables... yes
checking how to create a pax tar archive... gnutar
checking dependency style of gcc... gcc3
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports nested variables... (cached) yes
checking for a sed that does not truncate output... /usr/bin/sed
checking for gawk... (cached) mawk
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking how to run the C preprocessor... gcc -E
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking for ar... ar
checking the archiver (ar) interface... ar
checking for markdown... no
checking for asciidoc... no
checking for asciidoctor... no
configure: WARNING: ASCIIDOC ${SHELL} /home/ak/git/adwm/scripts/missing asciidoc is not supported.
checking for a2x... no
checking for asciidoctor... no
configure: WARNING: ASCIIMAN ${SHELL} /home/ak/git/adwm/scripts/missing a2x is not supported.
checking for lynx... no
checking for links... no
checking for a sed that does not truncate output... (cached) /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking how to print strings... printf
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for shl_load... no
checking for shl_load in -ldld... no
checking for dlopen... no
checking for dlopen in -ldl... yes
checking whether a program can dlopen itself... yes
checking whether a statically linked program can dlopen itself... no
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.14.0... yes
## ------------ ##
## Header Files ##
## ------------ ##
checking for ANSI C header files... (cached) yes
checking for X... libraries , headers 
checking for gethostbyname... yes
checking for connect... yes
checking for remove... yes
checking for shmat... yes
checking for IceConnectionNumber in -lICE... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking malloc.h usability... yes
checking malloc.h presence... yes
checking for malloc.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for strings.h... (cached) yes
checking for unistd.h... (cached) yes
## ------------------------------ ##
## Typedefs, Structures, Compiler ##
## ------------------------------ ##
checking for pid_t... yes
checking for size_t... yes
## ----------------- ##
## Library Functions ##
## ----------------- ##
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking whether lstat correctly handles trailing slash... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for getcwd... yes
checking for memmove... yes
checking for regcomp... yes
checking for select... yes
checking for setlocale... yes
checking for strchr... yes
checking for strdup... yes
checking for strerror... yes
checking for strrchr... yes
## ----------------------- ##
## X11 Extension Libraries ##
## ----------------------- ##
checking for X11... yes
checking for XFIXES... yes
checking for XDAMAGE... yes
checking for XCOMPOSITE... yes
checking for XRANDR... yes
checking for XINERAMA... yes
checking for XSYNC... yes
checking for XSHAPE... yes
checking for SMLIB... yes
checking for SN... no
## ------------------- ##
## Rendering Libraries ##
## ------------------- ##
checking for XRENDER... yes
checking for xrender use... no
checking for PIXBUF... yes
checking for gdk-pixbuf use... no
checking for IMLIB2... no
checking for imlib2 use... no
checking for XCAIRO... yes
checking for xcairo use... no
## ----------------------- ##
## Image Loading Libraries ##
## ----------------------- ##
checking for XPM... no
checking for LIBPNG... yes
checking for LIBJPEG... no
checking for LIBSVG... no
## -------------- ##
## Font Rendering ##
## -------------- ##
checking for XFT... yes
checking for xft use... no
checking for PANGOXFT... yes
checking for pango xft use... no
checking for PANGOCAIRO... yes
checking for pango cairo use... no
checking for debug support... no
## ------------------------------ ##
## Foreign Window Manager Support ##
## ------------------------------ ##
checking for blackbox support... no
checking for fluxbox support... no
checking for icewm support... no
checking for openbox support... no
checking for metacity support... no
checking for mutter support... no
checking for pekwm support... no
checking for waimea support... no
checking for wmaker support... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating doc/Makefile
config.status: creating doc/adwm.1
config.status: creating doc/adwm-config.5
config.status: creating doc/adwm-keys.5
config.status: creating doc/adwm-style.5
config.status: creating doc/adwm-theme.5
config.status: creating doc/adwm-dock.5
config.status: creating data/Makefile
config.status: creating src/autoconf.h
config.status: src/autoconf.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands

**Comment by bbidulock** [comment]
This line:

    checking for XPM... no

Load libxpm and your troubles will go away.

**Comment by bbidulock** [comment]
On another note, you should also load libjpeg and libsvg so that adwm can render jpeg and svg images.

**Comment by Awan** [comment]
I have installed them. But still have no success compiling it.

```
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports the include directive... yes (GNU style)
checking whether make supports nested variables... yes
checking how to create a pax tar archive... gnutar
checking dependency style of gcc... gcc3
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports nested variables... (cached) yes
checking for a sed that does not truncate output... /usr/bin/sed
checking for gawk... (cached) mawk
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking how to run the C preprocessor... gcc -E
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking for ar... ar
checking the archiver (ar) interface... ar
checking for markdown... no
checking for asciidoc... no
checking for asciidoctor... no
checking for a2x... no
checking for asciidoctor... no
checking for lynx... no
checking for links... no
checking for a sed that does not truncate output... (cached) /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking how to print strings... printf
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu
format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format...
func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared
libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for shl_load... no
checking for shl_load in -ldld... no
checking for dlopen... no
checking for dlopen in -ldl... yes
checking whether a program can dlopen itself... yes
checking whether a statically linked program can dlopen itself... no
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.14.0... yes
## ------------ ##
## Header Files ##
## ------------ ##
checking for ANSI C header files... (cached) yes
checking for X... libraries , headers 
checking for gethostbyname... yes
checking for connect... yes
checking for remove... yes
checking for shmat... yes
checking for IceConnectionNumber in -lICE... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking malloc.h usability... yes
checking malloc.h presence... yes
checking for malloc.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for strings.h... (cached) yes
checking for unistd.h... (cached) yes
## ------------------------------ ##
## Typedefs, Structures, Compiler ##
## ------------------------------ ##
checking for pid_t... yes
checking for size_t... yes
## ----------------- ##
## Library Functions ##
## ----------------- ##
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking whether lstat correctly handles trailing slash... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for getcwd... yes
checking for memmove... yes
checking for regcomp... yes
checking for select... yes
checking for setlocale... yes
checking for strchr... yes
checking for strdup... yes
checking for strerror... yes
checking for strrchr... yes
## ----------------------- ##
## X11 Extension Libraries ##
## ----------------------- ##
checking for X11... yes
checking for XFIXES... yes
checking for XDAMAGE... yes
checking for XCOMPOSITE... yes
checking for XRANDR... yes
checking for XINERAMA... yes
checking for XSYNC... yes
checking for XSHAPE... yes
checking for SMLIB... yes
checking for SN... no
## ------------------- ##
## Rendering Libraries ##
## ------------------- ##
checking for XRENDER... yes
checking for xrender use... no
checking for PIXBUF... yes
checking for gdk-pixbuf use... no
checking for IMLIB2... no
checking for imlib2 use... no
checking for XCAIRO... yes
checking for xcairo use... no
## ----------------------- ##
## Image Loading Libraries ##
## ----------------------- ##
checking for XPM... yes
checking for LIBPNG... yes
checking for LIBJPEG... yes
checking for LIBSVG... no
## -------------- ##
## Font Rendering ##
## -------------- ##
checking for XFT... yes
checking for xft use... no
checking for PANGOXFT... yes
checking for pango xft use... no
checking for PANGOCAIRO... yes
checking for pango cairo use... no
checking for debug support... no
## ------------------------------ ##
## Foreign Window Manager Support ##
## ------------------------------ ##
checking for blackbox support... no
checking for fluxbox support... no
checking for icewm support... no
checking for openbox support... no
checking for metacity support... no
checking for mutter support... no
checking for pekwm support... no
checking for waimea support... no
checking for wmaker support... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating doc/Makefile
config.status: creating doc/adwm.1
config.status: creating doc/adwm-config.5
config.status: creating doc/adwm-keys.5
config.status: creating doc/adwm-style.5
config.status: creating doc/adwm-theme.5
config.status: creating doc/adwm-dock.5
config.status: creating data/Makefile
config.status: creating src/autoconf.h
config.status: executing depfiles commands
config.status: executing libtool commands

```

and here is the make output.

```
╭─ak@nix in ~/git/adwm on master ✘ (origin/master)
╰ ▸▸▸▸▸▸▸▹▹▹ ❤ make
Making all in src
make[1]: Entering directory '/home/ak/git/adwm/src'
make  all-am
make[2]: Entering directory '/home/ak/git/adwm/src'
  CCLD     adwm
  /usr/bin/ld: adwm.o: in function `getappbutton':
  /home/ak/git/adwm/src/adwm.c:6265: undefined reference to `getappl'
  /usr/bin/ld: adwm.o: in function `unmanage':
  /home/ak/git/adwm/src/adwm.c:5584: undefined reference to `removeappl'
  collect2: error: ld returned 1 exit status
  make[2]: *** [Makefile:809: adwm] Error 1
  make[2]: Leaving directory '/home/ak/git/adwm/src'
  make[1]: *** [Makefile:619: all] Error 2
  make[1]: Leaving directory '/home/ak/git/adwm/src'
  make: *** [Makefile:462: all-recursive] Error 1

```

On 19/10, Brian Bidulock wrote:
>On another note, you should also load libjpeg and libsvg so that adwm can render jpeg and svg images.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bbidulock/adwm/issues/9#issuecomment-544223392


Abdullah

https://abdullah.today

C20F 2707 3025 2569 BAC5
534B 7820 6670 C19D 1580

**Comment by bbidulock** [comment]
That's this one:

    checking for SN... no

You should really load libstartup-notification-1.0 so that application icons can be displayed in title bars.  I also fixed this when the library is not available.

**Comment by bbidulock** [comment]
If you no longer have a problem, please close this issue.
